blog/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

blog/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail")
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about, name='about'),
    path('', views.homepage, name='homepage'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/accounts/models.py
from django.db import models

# Create your models here.

blog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS_CHOICES = [
    ('d', 'Draft'),
    ('p', 'Published'),
    ('w', 'Withdrawn'),
]


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default='d')
    thumbnail = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippit(self):
        return self.body[:47] + "..." if len(self.body) > 50 else self.body[:50]

blog/articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumbnail', 'status']

blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    if request.method == 'POST':
        # Validates form inputs
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('articles:list')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

blog/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

blog/blog/views.py
from django.shortcuts import render


def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')


def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

blog/accounts/templates/accounts/login.html
{% extends 'base_layout.html'%}

{% block content %}
  <h1>Log in!</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
     <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
  </form>
{% endblock %}

blog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}

{% block content %}
  <h1>Signup!</h1>
  <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

blog/articles/templates/articles/article_create.html
{% extends 'base_layout.html'%}

{% block content %}
<div class="create-article">
  <h2>Create a new article</h2>
  <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create">
  </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

blog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%}

{% block content %}
<div class="article-detail">
  <div class="article">
    <div class="article-img-parallax" style="background-image: url({{ article.thumbnail.url }})">
    </div>
    <div class="article-body">
      <h2>{{ article.title }}</h2>
      <p>{{ article.body }}</p>
      <p>{{ article.date }}</p>
    </div>
  </div>
</div>
{% endblock %}

blog/articles/templates/articles/article_list.html
{% extends 'base_layout.html'%}

{% block content %}
    <h1>Articles List</h1>
    <div class="articles">
        {% for article in articles %}
            {% if article.status == "p" %}
                <div class="article">
                    <h2><a href="{% url 'articles:detail' article.slug %}">{{ article.title }}</a></h2>
                    <p>{{ article.snippit }}</p>
                    <p>{{ article.date }}</p>
                    <p class="author">added by {{ article.author.username }}</p>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

blog/templates/about.html
{% extends 'base_layout.html'%}

{% block content %}
    <h1>About the blog</h1>
    <p>I built this mini project to learn the basics of Django, and it turned out to be quite simple to learn the basics</p>
    <p>I am hoping the use Django as the backend for my next freelance project, mainly because of the ease and speed of development.</p>
{% endblock %}

blog/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Django Blog!</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1 class="logo"><a href="{% url 'articles:list' %}">VIEW BLOG ARTICLES!</a></h1>
            <nav>
                <ul class="nav-list">
                    <li><a href="{% url 'homepage' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'articles:list' %}">Articles</a></li>
                    {% if user.is_authenticated == False %}
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    {% else %}
                    <li><a class="highlight" href="{% url 'articles:create' %}">New Article</a></li>
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

blog/templates/homepage.html
{% extends 'base_layout.html'%}

{% block content %}
    <h1>Welcome to the Django blog!</h1>
    <p>This is a very simple blog built using Django, a Python web framework.</p>
{% endblock %}